### ISSUE TITLE
Better API (IMO)

### ISSUE THREAD

**Issue by eorroe** [jonahvsweb/touchpoint-js#5]
I won't use this, but would like to give feedback:

How about an init function where you do:
## Init Function

```
TouchPoint.init({
  target: window,
  color: '#FFF',
  element: 'div',
  scale: 8,
  size: 20,
  z: 9999
});
```
## Setting properties

The following will allow changing the `properties` dynamically.

```
TouchPoint.setTarget(window);
TouchPoint.setColor('red');
TouchPoint.setElement('span');
TouchPoint.setScale(4);
TouchPoint.setSize(5);
TouchPoint.setZ(500);
```

I'd return `this` in the API so you can allow method chaining:

```
TouchPoint.setTarget(window)
    .setElement('span')
    .setColor('red')
    .setScale(4)
    .setSize(5)
    .setZ(500)
```

Unless returning something else is better, if so have the following method as well:

Just make sure each property is optional

```
TouchPoint.set({
 color: 'red'
});
```

And make the properties read only:

```
TouchPoint.color; // 'red'
TouchPoint.color = 'hi'; // throws error
```

Make setting it throw an Error so devs can stick to one style, and allows for method chaining.

That's all. Good Luck if you like the idea

**Comment by jonahvsweb** [comment]
@eorroe, that's interesting feedback on the API. I don't consider myself to be an advanced web dev, so input like this is appreciated. I'll consider your suggestions, maybe start a new branch. Thanks for the input and the time you took to write it!

**Comment by eorroe** [comment]
Whoa time flies completely forgot I did this, no problem glad to help 🙂
